import httpx
import json

BASE_URL = "http://127.0.0.1:8000/api/rest/v1"

CATEGORIES = [
    {"code": "flooring"},
    {"code": "clothing"},
    {"code": "electronics"},
    {"code": "accessories"},
]

FAMILIES = [
    {"code": "flooring"},
    {"code": "tshirts"},
    {"code": "laptops"},
]

ATTRIBUTES = [
    {"code": "description"},
    {"code": "commercial_description"},
    {"code": "gtin"},
    {"code": "sgvsb_number"},
    {"code": "bme_taxonomy_number"},
    {"code": "item_number_competitor"},
    {"code": "step_article_id"},
    {"code": "movex_nr"},
    {"code": "discount_group"},
    {"code": "price_group"},
    {"code": "price_method"},
    {"code": "availability"},
    {"code": "vat"},
    {"code": "blanket_order_group"},
    {"code": "automatic_bom_item"},
    {"code": "purchase_packaging_mandatory"},
    {"code": "sales_packaging_mandatory"},
    {"code": "stock_unit_of_measurement"},
    {"code": "package_unit_of_measurement"},
    {"code": "next_unit_pack_uom"},
    {"code": "price_unit_of_measurement"},
    {"code": "packaging"},
    {"code": "next_unit_pack"},
    {"code": "pallet"},
    {"code": "weight"},
    {"code": "volume"},
    {"code": "length"},
    {"code": "area"},
    {"code": "shoulder_length"},
    {"code": "width"},
    {"code": "factor"},
    {"code": "pallet_price"},
    {"code": "pallet_factor"},
    {"code": "private_customer_surcharge"},
    {"code": "price_increase_pct"},
    {"code": "lot_type"},
    {"code": "lot_factor"},
    {"code": "vendor"},
    {"code": "pick_up_address"},
    {"code": "parent_item"},
    {"code": "item_substitution"},
    {"code": "authorisation_in_c_cluster"},
    {"code": "freight_code"},
    {"code": "cost_code"},
    {"code": "consumption_item_lp"},
    {"code": "company_name"},
    {"code": "item_vendor"},
    {"code": "end_of_life_date"},
    {"code": "created_on"},
    {"code": "last_date_modified"},
    {"code": "created_by"},
    {"code": "changed_by"},
    {"code": "file_location_photo"},
    {"code": "file_location_drawing"},
    {"code": "file_location_drawing_1"},
    {"code": "file_location_drawing_2"},
    {"code": "file_location_drawing_3"},
    {"code": "file_location_drawing_4"},
    {"code": "file_location_drawing_5"},
    {"code": "safety_sheets_frs"},
    {"code": "safety_sheets_its"},
    {"code": "dangerous_goods_text"},
    {"code": "own_brand"},
    {"code": "freeze_class"},
    {"code": "abrasion_class"},
    {"code": "en_class"},
    {"code": "slip_resistance"},
    {"code": "series_name"},
    {"code": "optical_surface"},
    {"code": "article_category"},
    {"code": "promotion"},
    {"code": "shelf_life_months"},
    {"code": "mass_point_factor"},
    {"code": "team_number"},
    {"code": "base_stock_item"},
    {"code": "temporary_item"},
    {"code": "general_item"},
    {"code": "composed_item"},
    {"code": "service_item"},
    {"code": "shop_item"},
    {"code": "assembly"},
    {"code": "serial_number_required"},
    {"code": "lot_no"},
    {"code": "lot_no_mandatory_sales"},
    {"code": "purchase_order_blockade"},
    {"code": "display_on_orders"},
    {"code": "display_on_sales_quote"},
    {"code": "allow_sales_prices_with_0"},
    {"code": "customer_ok_required"},
    {"code": "no_discount"},
    {"code": "without_bom_linkage"},
    {"code": "country_origin_required"},
    {"code": "separate_lines_per_position"},
    {"code": "maintenance_via_step"},
    {"code": "step_upload_needed"},
    {"code": "template_item_only_quotes"},
    {"code": "not_allowed_in_quotation"},
    {"code": "exclude_excess_inventory"},
    {"code": "hide_sales_prices"},
    {"code": "record_ok"},
    {"code": "increase_gross_sales_price"},
    {"code": "print_on_purchase_order"},
    {"code": "print_on_direct_sales_order"},
    {"code": "kaba"},
]

V = lambda data, locale=None, scope=None: [{"data": data, "locale": locale, "scope": scope}]  # noqa

PRODUCTS = [
    {
        "identifier": "FLOOR-001",
        "family": "flooring",
        "categories": ["flooring"],
        "values": {
            "description": V("Natural Oak Herringbone Parquet"),
            "commercial_description": V("Premium solid oak herringbone flooring, UV lacquered"),
            "gtin": V("4006975001001"),
            "discount_group": V("FLOOR-A"),
            "price_group": V("PG-01"),
            "availability": V("10"),
            "vendor": V("VENDOR-OAK-001"),
            "freight_code": V("FRACHT-A"),
            "company_name": V("BMS Europe"),
            "item_vendor": V("OAK-12345"),
            "stock_unit_of_measurement": V("m2"),
            "package_unit_of_measurement": V("PAK"),
            "price_unit_of_measurement": V("m2"),
            "packaging": V(2),
            "next_unit_pack": V(10),
            "pallet": V("EUR-1"),
            "weight": V(8.5),
            "volume": V(0.018),
            "length": V(1.2),
            "area": V(2.0),
            "shoulder_length": V(15),
            "width": V(120),
            "factor": V(1.0),
            "pallet_price": V(485.00),
            "pallet_factor": V(40.0),
            "own_brand": V("OAK-PREMIUM"),
            "freeze_class": V("F0"),
            "abrasion_class": V("AC4"),
            "en_class": V("EN13489"),
            "slip_resistance": V("R10"),
            "series_name": V("Heritage"),
            "promotion": V("SPRING2026"),
            "shelf_life_months": V(240),
            "end_of_life_date": V("2040-12-31"),
            "created_by": V("ADMIN"),
            "changed_by": V("IMPORT"),
            "base_stock_item": V(True),
            "general_item": V(True),
            "display_on_orders": V(True),
            "display_on_sales_quote": V(True),
            "record_ok": V(True),
            "country_origin_required": V(True),
            "lot_no": V(False),
            "service_item": V(False),
        },
    },
    {
        "identifier": "FLOOR-002",
        "family": "flooring",
        "categories": ["flooring"],
        "values": {
            "description": V("Luxury Vinyl Plank — Light Grey"),
            "commercial_description": V("Click-lock LVP 4mm wear layer, waterproof"),
            "gtin": V("4006975001002"),
            "discount_group": V("FLOOR-B"),
            "price_group": V("PG-02"),
            "availability": V("10"),
            "vendor": V("VENDOR-VIN-001"),
            "freight_code": V("FRACHT-A"),
            "stock_unit_of_measurement": V("m2"),
            "package_unit_of_measurement": V("PAK"),
            "price_unit_of_measurement": V("m2"),
            "packaging": V(2),
            "next_unit_pack": V(20),
            "weight": V(5.8),
            "volume": V(0.012),
            "length": V(1.22),
            "area": V(2.1),
            "shoulder_length": V(4),
            "width": V(182),
            "factor": V(1.0),
            "pallet_price": V(312.00),
            "pallet_factor": V(50.0),
            "own_brand": V("VINYL-PRO"),
            "freeze_class": V("F2"),
            "abrasion_class": V("AC5"),
            "slip_resistance": V("R9"),
            "series_name": V("ModernLiving"),
            "created_by": V("ADMIN"),
            "changed_by": V("IMPORT"),
            "base_stock_item": V(True),
            "general_item": V(True),
            "display_on_orders": V(True),
            "record_ok": V(True),
            "lot_no": V(False),
            "service_item": V(False),
        },
    },
    {
        "identifier": "FLOOR-003",
        "family": "flooring",
        "categories": ["flooring"],
        "values": {
            "description": V("Porcelain Floor Tile 60x60 — White Matt"),
            "commercial_description": V("Rectified porcelain tile, R10 slip class"),
            "gtin": V("4006975001003"),
            "discount_group": V("TILE-A"),
            "price_group": V("PG-03"),
            "availability": V("10"),
            "vendor": V("VENDOR-TILE-001"),
            "freight_code": V("FRACHT-B"),
            "stock_unit_of_measurement": V("m2"),
            "package_unit_of_measurement": V("BOX"),
            "packaging": V(1),
            "next_unit_pack": V(12),
            "weight": V(18.0),
            "volume": V(0.02),
            "length": V(0.60),
            "area": V(0.36),
            "shoulder_length": V(10),
            "width": V(600),
            "pallet_price": V(890.00),
            "pallet_factor": V(30.0),
            "own_brand": V("TILE-CLASSIC"),
            "freeze_class": V("F2"),
            "abrasion_class": V("PEI5"),
            "en_class": V("ISO13006"),
            "slip_resistance": V("R10"),
            "created_by": V("ADMIN"),
            "changed_by": V("BUYER"),
            "base_stock_item": V(True),
            "general_item": V(True),
            "display_on_orders": V(True),
            "record_ok": V(True),
            "lot_no": V(True),
            "lot_no_mandatory_sales": V(True),
        },
    },
    {
        "identifier": "FLOOR-004",
        "family": "flooring",
        "categories": ["flooring"],
        "values": {
            "description": V("Laminate Flooring AC4 — Smoked Oak"),
            "gtin": V("4006975001004"),
            "discount_group": V("FLOOR-A"),
            "price_group": V("PG-01"),
            "availability": V("10"),
            "vendor": V("VENDOR-LAM-001"),
            "stock_unit_of_measurement": V("m2"),
            "packaging": V(2),
            "weight": V(7.2),
            "length": V(1.38),
            "shoulder_length": V(8),
            "width": V(193),
            "abrasion_class": V("AC4"),
            "slip_resistance": V("R9"),
            "series_name": V("Classic"),
            "base_stock_item": V(True),
            "general_item": V(True),
            "display_on_orders": V(True),
            "record_ok": V(True),
        },
    },
    {
        "identifier": "FLOOR-005",
        "family": "flooring",
        "categories": ["flooring"],
        "values": {
            "description": V("Cork Flooring — Natural Brown"),
            "gtin": V("4006975001005"),
            "discount_group": V("FLOOR-C"),
            "price_group": V("PG-02"),
            "availability": V("20"),
            "vendor": V("VENDOR-CORK-001"),
            "stock_unit_of_measurement": V("m2"),
            "packaging": V(2),
            "weight": V(4.1),
            "shoulder_length": V(10),
            "width": V(305),
            "freeze_class": V("F0"),
            "abrasion_class": V("AC3"),
            "series_name": V("Eco"),
            "shelf_life_months": V(120),
            "base_stock_item": V(False),
            "general_item": V(True),
            "display_on_orders": V(True),
            "record_ok": V(True),
            "end_of_life_date": V("2028-06-30"),
        },
    },
    {
        "identifier": "FLOOR-006",
        "family": "flooring",
        "categories": ["flooring"],
        "values": {
            "description": V("Rubber Sports Flooring 6mm — Black"),
            "commercial_description": V("Recycled EPDM rubber, suitable for gyms"),
            "gtin": V("4006975001006"),
            "discount_group": V("SPORTS-A"),
            "availability": V("10"),
            "vendor": V("VENDOR-RUB-001"),
            "stock_unit_of_measurement": V("m2"),
            "packaging": V(10),
            "weight": V(12.0),
            "shoulder_length": V(6),
            "width": V(1000),
            "abrasion_class": V("AC5"),
            "slip_resistance": V("R11"),
            "dangerous_goods_text": V("None"),
            "base_stock_item": V(True),
            "general_item": V(True),
            "display_on_orders": V(True),
            "record_ok": V(True),
            "lot_no": V(False),
        },
    },
    {
        "identifier": "SAN-001",
        "family": "flooring",
        "categories": ["accessories"],
        "values": {
            "description": V("Shower Drain Stainless Steel"),
            "commercial_description": V("Linear shower drain, polished stainless steel, 80cm"),
            "gtin": V("4006975002001"),
            "sgvsb_number": V("CH-SAN-20456"),
            "discount_group": V("SAN-A"),
            "price_group": V("PG-03"),
            "availability": V("10"),
            "vendor": V("VENDOR-SAN-001"),
            "stock_unit_of_measurement": V("STK"),
            "weight": V(1.4),
            "item_vendor": V("SANV-8800"),
            "created_by": V("ADMIN"),
            "changed_by": V("BUYER"),
            "base_stock_item": V(True),
            "general_item": V(True),
            "display_on_orders": V(True),
            "record_ok": V(True),
            "country_origin_required": V(True),
        },
    },
    {
        "identifier": "ACC-001",
        "family": "flooring",
        "categories": ["accessories"],
        "values": {
            "description": V("Transition Profile T-Bar Aluminium"),
            "gtin": V("4006975003001"),
            "discount_group": V("ACC-A"),
            "availability": V("10"),
            "vendor": V("VENDOR-PROF-001"),
            "stock_unit_of_measurement": V("STK"),
            "weight": V(0.45),
            "length": V(0.90),
            "own_brand": V("PROFILES"),
            "base_stock_item": V(True),
            "general_item": V(True),
            "display_on_orders": V(True),
            "record_ok": V(True),
        },
    },
    {
        "identifier": "ACC-002",
        "family": "flooring",
        "categories": ["accessories"],
        "values": {
            "description": V("Underlay Foam 3mm"),
            "gtin": V("4006975003002"),
            "discount_group": V("ACC-B"),
            "availability": V("10"),
            "vendor": V("VENDOR-UND-001"),
            "stock_unit_of_measurement": V("m2"),
            "packaging": V(10),
            "weight": V(0.35),
            "area": V(10.0),
            "shelf_life_months": V(60),
            "base_stock_item": V(True),
            "general_item": V(True),
            "record_ok": V(True),
        },
    },
    {
        "identifier": "tshirt-001",
        "family": "tshirts",
        "categories": ["clothing"],
        "values": {
            "description": V("Awesome T-Shirt"),
            "commercial_description": V("100% cotton, preshrunk, available in S/M/L/XL"),
            "gtin": V("4006975099001"),
            "vendor": V("VENDOR-TEX-001"),
            "freight_code": V("FRACHT-C"),
            "weight": V(0.25),
            "stock_unit_of_measurement": V("STK"),
            "base_stock_item": V(True),
            "general_item": V(True),
            "shop_item": V(True),
            "display_on_orders": V(True),
            "record_ok": V(True),
        },
    },
    {
        "identifier": "tshirt-002",
        "family": "tshirts",
        "categories": ["clothing"],
        "values": {
            "description": V("Basic White Tee"),
            "gtin": V("4006975099002"),
            "vendor": V("VENDOR-TEX-001"),
            "weight": V(0.22),
            "stock_unit_of_measurement": V("STK"),
            "base_stock_item": V(False),
            "general_item": V(True),
            "shop_item": V(True),
            "record_ok": V(True),
            "promotion": V("CLEARANCE"),
        },
    },
    {
        "identifier": "laptop-001",
        "family": "laptops",
        "categories": ["electronics"],
        "values": {
            "description": V('Pro Dev Laptop 15"'),
            "commercial_description": V("Intel i9, 32GB RAM, 1TB NVMe SSD"),
            "gtin": V("4006975088001"),
            "vendor": V("VENDOR-TECH-001"),
            "freight_code": V("FRACHT-D"),
            "weight": V(1.8),
            "stock_unit_of_measurement": V("STK"),
            "shelf_life_months": V(60),
            "base_stock_item": V(True),
            "general_item": V(True),
            "display_on_orders": V(True),
            "record_ok": V(True),
            "serial_number_required": V(True),
            "country_origin_required": V(True),
        },
    },
    {
        "identifier": "laptop-002",
        "family": "laptops",
        "categories": ["electronics"],
        "values": {
            "description": V('Budget Laptop 14"'),
            "gtin": V("4006975088002"),
            "vendor": V("VENDOR-TECH-002"),
            "weight": V(1.4),
            "stock_unit_of_measurement": V("STK"),
            "shelf_life_months": V(36),
            "base_stock_item": V(False),
            "general_item": V(True),
            "display_on_orders": V(True),
            "record_ok": V(True),
            "serial_number_required": V(True),
            "end_of_life_date": V("2027-12-31"),
        },
    },
    {
        "identifier": "SRV-001",
        "family": "flooring",
        "categories": ["accessories"],
        "values": {
            "description": V("Professional Installation Service"),
            "commercial_description": V("Floor installation by certified technicians, per m2"),
            "discount_group": V("SVC-A"),
            "price_group": V("PG-SVC"),
            "availability": V("10"),
            "vendor": V("BMS-INTERNAL"),
            "stock_unit_of_measurement": V("m2"),
            "company_name": V("BMS Europe"),
            "service_item": V(True),
            "general_item": V(True),
            "display_on_orders": V(True),
            "display_on_sales_quote": V(True),
            "record_ok": V(True),
            "lot_no": V(False),
            "not_allowed_in_quotation": V(False),
        },
    },
    {
        "identifier": "FLOOR-EOL",
        "family": "flooring",
        "categories": ["flooring"],
        "values": {
            "description": V("Discontinued Carpet Tiles — Charcoal"),
            "gtin": V("4006975099999"),
            "discount_group": V("FLOOR-A"),
            "availability": V("90"),
            "vendor": V("VENDOR-CARP-001"),
            "stock_unit_of_measurement": V("m2"),
            "weight": V(4.5),
            "abrasion_class": V("AC3"),
            "end_of_life_date": V("2026-06-30"),
            "base_stock_item": V(False),
            "general_item": V(False),
            "display_on_orders": V(False),
            "display_on_sales_quote": V(False),
            "record_ok": V(True),
            "exclude_excess_inventory": V(True),
        },
    },
]


def create_entity(endpoint: str, pk_field: str, item: dict) -> None:
    code = item[pk_field]
    response = httpx.get(f"{BASE_URL}/{endpoint}/{code}")
    if response.status_code == 200:
        print(f"✅ [{endpoint}] '{code}' already exists.")
        return
    response = httpx.post(f"{BASE_URL}/{endpoint}", json=item)
    if response.status_code == 201:
        print(f"🚀 [{endpoint}] Created '{code}'.")
    else:
        print(f"❌ [{endpoint}] Failed '{code}': {response.status_code} - {response.text}")


def seed_products_ndjson() -> None:
    print("📦 Bulk inserting products via NDJSON...")
    payload = "\n".join(json.dumps(p) for p in PRODUCTS) + "\n"
    headers = {"Content-Type": "application/vnd.akeneo.collection+json"}
    response = httpx.patch(f"{BASE_URL}/products", content=payload, headers=headers)
    if response.status_code == 200:
        for line in response.text.strip().split("\n"):
            if line:
                res = json.loads(line)
                print(f"   - Product '{res.get('identifier', '?')}': Status {res.get('status_code')}")
    else:
        print(f"❌ Failed: {response.status_code} - {response.text}")


def main() -> None:
    print("🌱 Seeding Mock Akeneo API...\n")

    for category in CATEGORIES:
        create_entity("categories", "code", category)

    for family in FAMILIES:
        create_entity("families", "code", family)

    for attr in ATTRIBUTES:
        create_entity("attributes", "code", attr)

    print("")
    seed_products_ndjson()
    print("\n✅ Seeding complete!")


if __name__ == "__main__":
    main()
